<?php

namespace App\Support;

class SiteDefaults
{
    public static function navItems(): array
    {
        return [
            ['label' => 'Home', 'href' => '/#top', 'visible' => true],
            ['label' => 'New to Australia', 'href' => '/new-to-australia', 'visible' => true],
            ['label' => 'New to New Zealand', 'href' => '/new-to-new-zealand', 'visible' => true],
            [
                'label' => 'Settlement Services',
                'href' => '/settlement-services',
                'visible' => true,
                'submenu' => [
                    ['label' => 'service', 'href' => '/settlement-services'],
                    ['label' => 'Stage 01 - Arrive', 'href' => '/settlement-services/arrive'],
                    ['label' => 'Stage 02 - Settle', 'href' => '/settlement-services/settle'],
                    ['label' => 'Stage 03 - Work & Invest', 'href' => '/settlement-services/work-invest'],
                    ['label' => 'Stage 04 - Enjoy', 'href' => '/settlement-services/enjoy'],
                ]
            ],
            ['label' => 'Blog', 'href' => '/blog', 'visible' => true],
            ['label' => 'Directory', 'href' => '/directory', 'visible' => true],
            ['label' => 'Migration Services', 'href' => '/migration-services', 'visible' => true],
            ['label' => 'About', 'href' => '/about', 'visible' => true],
            ['label' => 'Contact', 'href' => '/contact', 'visible' => true],
        ];
    }

    public static function visibleNavItems(): array
    {
        return array_values(array_filter(
            self::navItems(),
            static fn (array $item): bool => $item['visible'] ?? true
        ));
    }

    public static function featuredGuides(): array
    {
        return [
            [
                'title' => 'New to Australia',
                'eyebrow' => 'Arrival guide',
                'description' => 'Checklist-led guidance for before you arrive, your first week, healthcare, banking, work, and staying connected.',
                'href' => '/new-to-australia',
            ],
            [
                'title' => 'Settlement Services',
                'eyebrow' => 'Full package guidance',
                'description' => 'Personalised support from airport pickup to securing your first rental and building your community.',
                'href' => '/settlement-services',
            ],
        ];
    }

    public static function blogPosts(): array
    {
        return [
            [
                'slug' => 'best-banks-for-new-arrivals-australia',
                'title' => 'Best Banks for New Arrivals in Australia',
                'category' => 'Banking',
                'excerpt' => 'A practical comparison of newcomer-friendly bank options, fees, and account setup choices.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-04-02 10:00:00',
                'reading_time' => '8 min read',
                'image' => 'Best Banks for New Arrivals in Australia.webp',
                'image_class' => 'guide-feature-card__image--slate',
                'intro_content' => 'A strong banking setup is one of the easiest ways to reduce friction in your first month. The goal is not just opening any account quickly, but choosing one that works well for international transfers, everyday payments, and the admin you need to handle after arrival.',
                'checks_content' => 'Check whether you can start the account setup before arrival, what the monthly account cost really is, how easy it is to verify your identity, and whether the bank makes international transfers simple. For many newcomers, the easiest option is the one that removes paperwork and keeps fees transparent.',
                'next_steps_content' => 'If you need the fastest route, shortlist one specialist option and one traditional bank, compare their onboarding friction, and move forward with the account you can actually use in the next seven days.',
                'is_published' => true,
                'is_featured_home' => true,
            ],
            [
                'slug' => 'where-expats-should-rent-first',
                'title' => 'Where Expats Should Rent First in Australia',
                'category' => 'Housing',
                'excerpt' => 'How to choose your first suburb, test commute times, and avoid locking in the wrong area too early.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-04-01 10:00:00',
                'reading_time' => '9 min read',
                'image' => 'Where Expats Should Rent First in Australia.avif',
                'image_class' => 'guide-feature-card__image--sand',
                'intro_content' => 'The right first suburb is rarely the cheapest or the trendiest. It is the one that gives you transport access, enough flexibility to learn the city, and fewer expensive mistakes while you are still finding your routine.',
                'checks_content' => 'Before signing anything long-term, compare commute time, short-term furnished options, local grocery access, and how easy the area feels without a car. New arrivals usually benefit from testing a suburb before committing to a twelve-month plan.',
                'next_steps_content' => 'If you are still choosing between areas, take one short-term stay close to work or study and use the first two weeks to inspect suburbs in person before locking in a long lease.',
                'is_published' => true,
                'is_featured_home' => true,
            ],
            [
                'slug' => 'moving-checklist-before-you-fly',
                'title' => 'Moving Checklist: What to Sort Before You Fly',
                'category' => 'Moving',
                'excerpt' => 'The documents, bookings, and first-week admin to handle before departure.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-30 10:00:00',
                'reading_time' => '7 min read',
                'image' => 'Moving Checklist What to Sort Before You Fly.webp',
                'image_class' => 'guide-feature-card__image--teal',
                'intro_content' => 'A calmer move starts before the airport. The biggest wins usually come from sorting the boring admin early, because it frees up your first week to focus on arrival instead of missing paperwork or scrambling for basics.',
                'checks_content' => 'Check your passport validity, visa approval, accommodation confirmation, banking plan, Medicare or insurance preparation, and what you need for local phone service. Anything tied to identity or access becomes harder under time pressure after you land.',
                'next_steps_content' => 'Use one checklist that covers travel, money, health, and communication, then book a single hour to finish the items that can only be done before departure.',
                'is_published' => true,
                'is_featured_home' => true,
            ],
            [
                'slug' => 'medicare-and-private-cover-explained',
                'title' => 'Medicare and Private Cover Explained for Migrants',
                'category' => 'Healthcare',
                'excerpt' => 'A simple breakdown of Medicare eligibility, interim cover, and what to arrange early.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-28 10:00:00',
                'reading_time' => '6 min read',
                'image' => 'Medicare and Private Cover Explained for Migrants.webp',
                'image_class' => 'guide-feature-card__image--teal',
                'intro_content' => 'Healthcare is one of the easiest areas to misunderstand when you are moving quickly. Medicare rules, waiting periods, and private cover options all depend on visa type and timing.',
                'checks_content' => 'Check whether you are Medicare-eligible, what interim cover you may need, and whether private cover is a compliance requirement or simply a practical safety net during the move.',
                'next_steps_content' => 'When the answer is still unclear, use a trusted insurance partner or agent who works with migrants rather than waiting until after arrival to find out you have a gap.',
                'is_published' => true,
                'is_featured_home' => false,
            ],
            [
                'slug' => 'how-to-find-work-faster-after-arrival',
                'title' => 'How to Find Work Faster After Arrival',
                'category' => 'Working',
                'excerpt' => 'CV setup, TFN timing, and the practical first steps that make job applications smoother.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-26 10:00:00',
                'reading_time' => '10 min read',
                'image' => 'How to Find Work Faster After Arrival.webp',
                'image_class' => 'guide-feature-card__image--slate',
                'intro_content' => 'Finding work faster usually comes down to sequence. A local-style CV, the right legal setup, and a clear shortlist of roles will do more than sending dozens of rushed applications.',
                'checks_content' => 'Check your TFN timing, local contact details, suburb commute range, and whether your CV reflects the market you are entering. Many newcomers lose time because their job search starts before the admin is ready.',
                'next_steps_content' => 'Get your paperwork and local contact details in place first, then build a shortlist of target roles and tailor your applications instead of applying to everything at once.',
                'is_published' => true,
                'is_featured_home' => false,
            ],
            [
                'slug' => 'everyday-life-tips-for-expats',
                'title' => 'Everyday Life Tips for Expats in Australia',
                'category' => 'Lifestyle',
                'excerpt' => 'Small practical habits that make the first month feel more manageable and less overwhelming.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-25 10:00:00',
                'reading_time' => '5 min read',
                'image' => 'Everyday Life Tips for Expats in Australia.webp',
                'image_class' => 'guide-feature-card__image--sand',
                'intro_content' => 'The first month feels easier when you reduce small decisions. Repeating a few good routines matters more than trying to optimise everything at once.',
                'checks_content' => 'Focus on transport, grocery routines, basic local apps, and a realistic weekly admin list. That creates stability quickly and makes the bigger decisions less overwhelming.',
                'next_steps_content' => 'Pick three routines to simplify first: how you get around, where you shop, and when you handle relocation admin each week.',
                'is_published' => true,
                'is_featured_home' => false,
            ],
            [
                'slug' => 'transfer-money-without-losing-on-fees',
                'title' => 'How to Transfer Money Without Losing on Fees',
                'category' => 'Banking',
                'excerpt' => 'Compare spreads, fees, and practical timing when sending money internationally.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-22 10:00:00',
                'reading_time' => '8 min read',
                'image' => null,
                'image_class' => 'guide-feature-card__image--slate',
                'intro_content' => 'The real cost of a money transfer is often hidden in the exchange rate rather than the headline fee. That makes comparison harder unless you check the full landed amount.',
                'checks_content' => 'Compare the exchange rate spread, transfer speed, payout method, and whether your corridor attracts extra charges. The cheapest-looking option on the surface is not always the cheapest in practice.',
                'next_steps_content' => 'Run one real transfer scenario through two or three providers before moving a large amount so you can compare the actual destination amount side by side.',
                'is_published' => true,
                'is_featured_home' => false,
            ],
            [
                'slug' => 'student-housing-tips-before-semester',
                'title' => 'Student Housing Tips Before Semester Starts',
                'category' => 'Housing',
                'excerpt' => 'What students should book early, what can wait, and how to avoid rushed rental decisions.',
                'author_name' => 'SettleANZ Team',
                'published_at' => '2026-03-20 10:00:00',
                'reading_time' => '6 min read',
                'image' => null,
                'image_class' => 'guide-feature-card__image--sand',
                'intro_content' => 'Students often feel pressure to sort housing too early or too late. The best approach is usually a short initial stay and a clearer understanding of campus distance, transport, and budgeting before committing.',
                'checks_content' => 'Check what your university recommends, how long you can stay temporarily, and whether the area works for transport, groceries, and safety rather than just the weekly rent.',
                'next_steps_content' => 'Book a flexible first stay, then inspect local options once you arrive instead of making a rushed long-term decision from overseas.',
                'is_published' => true,
                'is_featured_home' => false,
            ],
        ];
    }

    public static function directoryListings(): array
    {
        return [
            [
                'slug' => 'southern-cross-migration',
                'name' => 'Southern Cross Migration',
                'category' => 'Immigration Lawyers',
                'city' => 'Sydney',
                'rating' => 4.9,
                'featured' => true,
                'description' => 'Registered migration support for skilled, partner, and complex visa pathways.',
                'full_description' => 'Southern Cross Migration supports expats with visa planning, eligibility reviews, employer-sponsored pathways, and application strategy. The service is designed for newcomers who want practical guidance rather than vague general advice.',
                'services' => ['Visa eligibility reviews', 'Employer-sponsored pathways', 'Partner visa strategy', 'Application document guidance'],
                'phone' => '+61 2 8000 1200',
                'email' => 'hello@southerncrossmigration.example',
                'website' => 'https://example.com/southern-cross-migration',
                'whatsapp' => 'https://wa.me/61000000001?text=Hi%20Southern%20Cross%20Migration',
                'booking_url' => 'https://calendly.com/example/southern-cross-migration',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'harbour-visa-law',
                'name' => 'Harbour Visa Law',
                'category' => 'Immigration Lawyers',
                'city' => 'Melbourne',
                'rating' => 4.8,
                'featured' => true,
                'description' => 'Clear visa pathway advice for partners, skilled workers, and employer-sponsored applications.',
                'full_description' => 'Harbour Visa Law supports newcomers with visa strategy, document preparation, and practical guidance across the most common migration pathways. The focus is on helping clients move forward with a clear next step.',
                'services' => ['Visa strategy sessions', 'Document preparation', 'Employer sponsorship guidance', 'Partner visa support'],
                'phone' => '+61 3 8000 2200',
                'email' => 'hello@harbourvisalaw.example',
                'website' => 'https://example.com/harbour-visa-law',
                'whatsapp' => 'https://wa.me/61000000004?text=Hi%20Harbour%20Visa%20Law',
                'booking_url' => 'https://calendly.com/example/harbour-visa-law',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'pacific-migration-advisory',
                'name' => 'Pacific Migration Advisory',
                'category' => 'Immigration Lawyers',
                'city' => 'Brisbane',
                'rating' => 4.7,
                'featured' => false,
                'description' => 'Support for student, working holiday, and family visa questions with a practical approach.',
                'full_description' => 'Pacific Migration Advisory helps expats understand visa options, prepare supporting documents, and avoid common mistakes that slow down an application. It is suited to people who want steady, practical advice.',
                'services' => ['Student visa guidance', 'Working holiday advice', 'Family visa planning', 'Application checklist reviews'],
                'phone' => '+61 7 8000 3300',
                'email' => 'team@pacificmigrationadvisory.example',
                'website' => 'https://example.com/pacific-migration-advisory',
                'whatsapp' => '',
                'booking_url' => 'https://calendly.com/example/pacific-migration-advisory',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'harbour-relocation-group',
                'name' => 'Harbour Relocation Group',
                'category' => 'Relocation Companies',
                'city' => 'Melbourne',
                'rating' => 4.8,
                'featured' => true,
                'description' => 'Hands-on suburb matching, school research, and home setup support for families.',
                'full_description' => 'Harbour Relocation Group helps families and professionals compare suburbs, short-term stays, and first-home options while coordinating the everyday logistics that make arrival smoother.',
                'services' => ['Suburb matching', 'School shortlists', 'Arrival setup planning', 'Housing search support'],
                'phone' => '+61 3 8000 4500',
                'email' => 'hello@harbourrelocation.example',
                'website' => 'https://example.com/harbour-relocation-group',
                'whatsapp' => 'https://wa.me/61000000002?text=Hi%20Harbour%20Relocation%20Group',
                'booking_url' => 'https://calendly.com/example/harbour-relocation-group',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'australia-finance-advisory',
                'name' => 'Australia Finance Advisory',
                'category' => 'Financial Advisors',
                'city' => 'Brisbane',
                'rating' => 4.7,
                'featured' => false,
                'description' => 'Financial planning support for expats managing tax, budgeting, and settlement decisions.',
                'full_description' => 'Australia Finance Advisory works with new arrivals who want clarity on budgeting, early financial setup, and the decisions that matter in the first year after moving.',
                'services' => ['Budget planning', 'Expat financial setup', 'Tax coordination referrals', 'Cash-flow planning'],
                'phone' => '+61 7 8000 7711',
                'email' => 'team@australiafinanceadvisory.example',
                'website' => 'https://example.com/australia-finance-advisory',
                'whatsapp' => '',
                'booking_url' => '',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'pacific-real-estate-expat-desk',
                'name' => 'Pacific Real Estate Expat Desk',
                'category' => 'Real Estate Agents',
                'city' => 'Auckland',
                'rating' => 4.8,
                'featured' => false,
                'description' => 'Rental search and relocation-friendly leasing support for newcomers to New Zealand.',
                'full_description' => 'Pacific Real Estate Expat Desk helps newcomers understand the local market, compare neighbourhoods, and navigate first-rental decisions with less stress.',
                'services' => ['Rental search support', 'Neighbourhood shortlists', 'Inspection coordination', 'Lease guidance'],
                'phone' => '+64 9 555 0190',
                'email' => 'desk@pacificrealestate.example',
                'website' => 'https://example.com/pacific-real-estate-expat-desk',
                'whatsapp' => '',
                'booking_url' => '',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'carebridge-health-network',
                'name' => 'CareBridge Health Network',
                'category' => 'Healthcare',
                'city' => 'Perth',
                'rating' => 4.6,
                'featured' => false,
                'description' => 'New-arrival healthcare navigation, insurance referrals, and local clinic introductions.',
                'full_description' => 'CareBridge Health Network supports expats who need help understanding health coverage, local care options, and where to start when Medicare is still unclear.',
                'services' => ['Health system orientation', 'Insurance referrals', 'Clinic introductions', 'Family healthcare planning'],
                'phone' => '+61 8 7000 2299',
                'email' => 'support@carebridgehealth.example',
                'website' => 'https://example.com/carebridge-health-network',
                'whatsapp' => 'https://wa.me/61000000003?text=Hi%20CareBridge%20Health%20Network',
                'booking_url' => '',
                'logo' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'global-school-search',
                'name' => 'Global School Search',
                'category' => 'International Schools',
                'city' => 'Sydney',
                'rating' => 4.9,
                'featured' => true,
                'description' => 'Family-focused support for comparing school options, enrolment timing, and suburb fit.',
                'full_description' => 'Global School Search helps families align suburb decisions with school options, enrolment timelines, and practical lifestyle needs so the move feels coordinated rather than fragmented.',
                'services' => ['School comparisons', 'Enrolment timing guidance', 'Suburb-school matching', 'Family relocation support'],
                'phone' => '+61 2 8123 7788',
                'email' => 'hello@globalschoolsearch.example',
                'website' => 'https://example.com/global-school-search',
                'whatsapp' => '',
                'booking_url' => '',
                'logo' => null,
                'is_published' => true,
            ],
        ];
    }

    public static function siteSettings(): array
    {
        return [
            'contact_email' => 'hello@settleanz.com',
            'contact_whatsapp' => 'https://wa.me/61000000000?text=Hi%20SettleANZ%2C%20I%20have%20a%20question.',
            'contact_response_time' => 'We usually respond within 24 hours.',
            'footer_whatsapp' => 'https://wa.me/61416874058?text=Hi%20SettleANZ%2C%20I%20would%20like%20help%20with%20my%20move.',
            'social_facebook' => 'https://www.facebook.com/profile.php?id=61590926305491',
            'social_instagram' => 'https://www.instagram.com/settleanzofficial/',
            'social_linkedin' => '#',
            'social_pinterest' => 'https://www.pinterest.com/SettleANZ/',
            'social_reddit' => 'https://www.reddit.com/user/settleANZ_official/',
            'social_tiktok' => 'https://www.tiktok.com/@settleanz',
            'social_youtube' => 'https://www.youtube.com/@SettleANZ',
            'founder_story_link' => '#',
            'migration_cta_label' => 'Book a Consultation',
            'directory_apply_link' => '/contact',
            'ai_assistant_enabled' => '1',
            'ai_assistant_title' => 'SettleANZ AI Assistant',
            'ai_assistant_subtitle' => 'Ask about housing, banking, TFN, Medicare, jobs, visas, and settling in Australia & New Zealand.',
            'ai_assistant_greeting' => 'Hi there! I can help with questions about housing, banking, TFN, Medicare, jobs, and settling into Australia or New Zealand. What are you working on?',
            'ai_assistant_system_prompt' => '',
            'ai_openai_api_key' => '',
            'ai_openai_base_url' => 'https://api.openai.com/v1',
            'ai_openai_model' => 'gpt-4o-mini',
            'ai_web_search_enabled' => '1',
            'ai_max_bullets' => '3',
            'ai_max_length' => '600',
            'ai_response_tone' => 'professional',
            'ai_include_page_links' => '1',
            'ai_show_sources' => '1',
            'ai_response_language' => 'en',
            'ai_response_format' => 'mixed',
            'ai_stay_focused' => '1',
            'ai_avoid_ai_phrases' => '1',
            'ai_use_real_examples' => '1',
            'ai_professional_disclaimer' => '1',
            'ai_uncertainty_handling' => 'say_uncertain',
            'ai_follow_up_phrase' => '',
            'ai_closing_phrase' => '',
        ];
    }
}
